# Generated by Django 6.0.3 on 2026-03-08 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_code', models.CharField(choices=[('dashboard', 'Dashboard'), ('patients', 'Patients'), ('appointments', 'Appointments'), ('doctors', 'Doctors'), ('lab', 'Laboratory'), ('treatment', 'Treatment Rooms'), ('billing', 'Cash Register / Billing'), ('reports', 'Reports'), ('settings_users', 'Users & Permissions')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'page_code')},
            },
        ),
    ]
