# Generated by Django 6.0.3 on 2026-03-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpagepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpagepermission',
            name='page_code',
            field=models.CharField(choices=[('dashboard', 'Boshqaruv paneli'), ('patients', 'Bemorlar'), ('appointments', 'Qabul va navbat'), ('doctors', 'Shifokorlar'), ('lab', 'Laboratoriya'), ('treatment', 'Davolash xonalari'), ('billing', 'Kassa / Billing'), ('reports', 'Hisobotlar'), ('settings_users', 'Foydalanuvchilar va ruxsatlar')], max_length=50),
        ),
    ]
