# Generated by Django 6.0.3 on 2026-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userpagepermission_page_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('registrator', 'Registrator'), ('cashier', 'Cashier'), ('doctor', 'Doctor'), ('lab_staff', 'Lab Staff'), ('treatment_staff', 'Treatment Room Staff')], max_length=40, unique=True),
        ),
    ]
