# Generated by Django 6.0.3 on 2026-04-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userpagepermission_page_code'),
        ('accounts', '0006_remove_role_name_choices'),
    ]

    operations = [
    ]
