# Generated by Django 6.0.3 on 2026-04-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260429_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpagepermission',
            name='page_code',
            field=models.CharField(choices=[('dashboard', 'Boshqaruv paneli'), ('patients', 'Bemorlar'), ('appointments', 'Qabul va navbat'), ('service_queue', 'Xizmat navbati'), ('mrt_queue', 'MRT Navbati'), ('doctors', 'Shifokorlar'), ('lab', 'Laboratoriya'), ('treatment', 'Davolash xonasi'), ('rooms', "Xonalar ro'yxati"), ('treatment_billing', "Yotoq to'lovlari"), ('cash_register', 'Kassa'), ('billing', "To'lovlar"), ('pricing', 'Xizmat narxlari'), ('accountant', 'Buxgalteriya'), ('income', 'Daromad analitika'), ('reports', 'Hisobotlar'), ('settings_users', 'Foydalanuvchilar va ruxsatlar')], max_length=50),
        ),
    ]
