# Generated by Django 6.0.3 on 2026-03-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treatment_rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("area_type", models.CharField(choices=[("floor", "Floor"), ("apartment", "Apartment")], default="floor", max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_areas",
                        to="clinics.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="treatment_areas", to="clinics.clinic"),
                ),
            ],
            options={
                "unique_together": {("clinic", "area_type", "name")},
            },
        ),
        migrations.AddField(
            model_name="treatmentroom",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="treatment_rooms.treatmentarea",
            ),
        ),
        migrations.AddField(
            model_name="treatmentroom",
            name="daily_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name="treatmentroom",
            unique_together={("clinic", "area", "name")},
        ),
    ]
