# Generated by Django 6.0.3 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treatment_rooms", "0002_treatmentarea_room_daily_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentroom",
            name="capacity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
