# Generated by Django 6.0.3 on 2026-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_rooms', '0003_treatmentroom_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentroom',
            options={'ordering': ['room_number', 'name']},
        ),
        migrations.AddField(
            model_name='treatmentroom',
            name='room_number',
            field=models.PositiveIntegerField(default=0, help_text='Numeric value for sorting'),
        ),
    ]
