# Generated by Django 6.0.3 on 2026-03-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treatment_rooms", "0003_treatmentroom_capacity"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="treatment_referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="treatment_rooms.treatmentreferral",
            ),
        ),
    ]
