# Generated by Django 6.0.3 on 2026-04-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_charge_treatment_charge_date_and_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_options',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='billing.service')),
            ],
            options={
                'unique_together': {('service', 'name')},
            },
        ),
    ]
