# Generated by Django 6.0.3 on 2026-03-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("billing", "0003_charge_treatment_charge_date_and_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceQueueTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("queue_date", models.DateField()),
                ("sequence_number", models.PositiveIntegerField()),
                ("queue_code", models.CharField(max_length=16)),
                ("status", models.CharField(choices=[("waiting", "Waiting"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="waiting", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_queue_tickets",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_queue_tickets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_queue_tickets",
                        to="patients.patient",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_tickets",
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "ordering": ["queue_date", "sequence_number", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "queue_date", "sequence_number"),
                        name="uniq_service_queue_daily_sequence",
                    )
                ],
            },
        ),
    ]
