# Generated by Django 6.0.3 on 2026-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_referring_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicequeueticket',
            name='referring_doctor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Yuborgan shifokor'),
        ),
    ]
