# Generated by Django 6.0.3 on 2026-05-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_referring_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Navbat raqami'),
        ),
    ]
