#!/bin/bash
set -e
# Treatment Room Daily Charge - Cron Setup Script
# Runs daily at 12:00 PM to auto-charge treatment room patients
PROJECT_DIR="/var/www/medservice-management-system-v2"
BACKEND_DIR="$PROJECT_DIR/backend"
VENV_PYTHON="$PROJECT_DIR/venv/bin/python"
LOG_FILE="/var/log/treatment_charges.log"
CRON_FILE="/etc/cron.d/treatment_daily_charge"
echo "=== Treatment Room Daily Charge Cron Setup ==="
# Verify virtual environment exists
if [ ! -f "$VENV_PYTHON" ]; then
    echo "ERROR: Virtual environment Python not found at $VENV_PYTHON"
    echo "Please ensure the project is set up correctly."
    exit 1
fi
# Verify Django management command works
echo "Testing management command..."
$VENV_PYTHON $BACKEND_DIR/manage.py run_treatment_daily_charge --help > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "ERROR: Cannot run Django management command"
    exit 1
fi
echo "OK - Management command works"
# Create log directory if needed
touch $LOG_FILE 2>/dev/null || sudo touch $LOG_FILE
# Create cron file
echo "Installing cron job to run at 12:00 PM daily..."
# Cron format: minute hour day-of-month month day-of-week
# 0 12 * * * = run at 12:00 PM every day
sudo tee $CRON_FILE > /dev/null << 'EOF'
# Treatment Room Daily Charge - Auto-generated by setup script
# Runs daily at 12:00 PM to charge treatment room patients
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
0 12 * * * root cd /var/www/medservice-management-system-v2/backend && /var/www/medservice-management-system-v2/venv/bin/python manage.py run_treatment_daily_charge --force >> /var/log/treatment_charges.log 2>&1
EOF
# Set proper permissions
sudo chmod 644 $CRON_FILE
# Verify cron is running
if systemctl is-active --quiet cron 2>/dev/null; then
    echo "Cron daemon is running"
elif systemctl is-active --quiet crond 2>/dev/null; then
    echo "Cron daemon (crond) is running"
else
    echo "WARNING: Cron daemon may not be running. Trying to start..."
    sudo systemctl start cron || sudo systemctl start crond || true
fi
# Reload cron to pick up new job
sudo systemctl reload cron 2>/dev/null || sudo systemctl reload crond 2>/dev/null || true
echo ""
echo "=== Setup Complete ==="
echo "Cron job installed: Runs daily at 12:00 PM"
echo "Log file: $LOG_FILE"
echo ""
echo "To verify the cron job is installed, run:"
echo "  sudo cat $CRON_FILE"
echo ""
echo "To test the charging command manually, run:"
echo "  cd $BACKEND_DIR && $VENV_PYTHON manage.py run_treatment_daily_charge --force"
echo ""
echo "To view logs, run:"
echo "  tail -f $LOG_FILE"
