# Generated by Django 6.0.3 on 2026-03-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
