# Generated by Django 6.0.3 on 2026-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='salary_percentage',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Treatment revenue share percentage (%)', max_digits=5),
        ),
    ]
